clspring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/teste}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:fatec}
spring.datasource.driver-class-name=org.postgresql.Driver


jwt.secret=${JWT_SECRET:qVSK9pWzP7q6HhMn3coOngnG/4fK5fF6e5AhzL1Af2I=}
crypto.secret=${CRYPTO_SECRET:U2FsdGVkX1+5r8b9v3J6hQ==}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL:nine.codek9@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:pdokrudazbubsqgz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=false
