package com.codenine.managementservice.dto.action;

public enum ActionType {
  ORDER_CREATED,
  ORDER_UPDATED,
  ORDER_CANCELLED,
  ORDER_STATUS_CHANGED,
  USER_CREATED,
  USER_ENABLED_CHANGED,
  USER_UPDATED,
  SECTION_CREATED,
  SECTION_UPDATED,
  PURCHASE_ORDER_CREATED,
  EMAIL_CHARGE_SENT,
  PURCHASE_ORDER_UPDATED,
  PURCHASE_ORDER_STATUS_UPDATED
}
