package com.codenine.managementservice.dto.notification;

public enum NotificationType {
  LOW_STOCK,
  CRITICAL_STOCK,
  OUT_OF_STOCK,
  REORDER_RECOMMENDATION,
  MIN_STOCK_TOO_LOW,
  ORDER_CREATED,
  ORDER_APPROVED,
  ORDER_PROCESSING,
  ORDER_COMPLETED,
  ORDER_CANCELLED,
  TRANSFER_CREATED,
  TRANSFER_COMPLETED,
  TRANSFER_CANCELLED,
  TRANSFER_DEADLINE_NEAR,
  TRANSFER_OVERDUE
}
